### ISSUE TITLE
implement individual labels for individual blobs

### ISSUE THREAD

**Issue by gregordecristoforo** [uit-cosmo/2d-propagating-blobs#42]
In order to track individual blobs over time give every blob an individual label. If multiple blobs overlap choose the blob with highest amplitude.

**Comment by leanderkirkeland** [comment]
With some changes to the model, i have made two extra label types:
simple diff:
Same as the one you created but with label for each created blob. The problem with this one is that it overwrites the old ones even if it has higher amplitude.
diff:
Takes into account the self.__density field, to chech if there already is a higher amplitude at the point, and does not overwrite it, but you get some gaps between the blobs.(this can be both good and bad). Here is an image of the last one. 

![Figure_1](https://user-images.githubusercontent.com/94841211/158586879-1de35c1c-4c22-4833-95f3-e66c2664770b.png)
 
Another thing is that this would not be a great set for CNN only, since if one blob leaves the image after say12 sec, then the image would not have label 1, but only higher, and as CNN treats each image seperatly, but this would be good for CNN-RNN where it is timedependent of the previous image. So i think if we use this on the models i use now, it would be just random and it would predict every pixel to be 0.
